name: MPI Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display directory contents
      run: |
        ls -la

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential openmpi-bin openmpi-common libopenmpi-dev

    - name: Verify MPI installation
      run: |
        mpic++ --version
        mpirun --version

    - name: Build MPI program
      run: |
        cd Project_3/Lab3_3/Lab3_3
        mpic++ -o mpi_root_finder Lab3_3.cpp

    - name: Run MPI program
      run: |
        cd Project_3/Lab3_3/Lab3_3
        echo "1 2 3" | mpirun --oversubscribe -np 4 ./mpi_root_finder

    - name: Check output
      run: |
        if [ -f Project_3/Lab3_3/Lab3_3/sequences.txt ]; then
          echo "Output file sequences.txt exists."
        else
          echo "Output file sequences.txt does not exist."
          exit 1
        fi
