name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MPI
      run: |
        sudo apt-get update
        sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev

    - name: Build
      run: |
        mpic++ -o Lab3_3 Lab3_3/Lab3_3/Lab3_3.cpp

    - name: Run tests
      run: |
        mpirun -np 4 ./Lab3_3
